# Generated by Django 3.2.4 on 2021-07-08 03:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210707_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='fotoTrabajo2',
            field=models.CharField(default='', max_length=200, verbose_name='Foto del trabajo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajo',
            name='fotoTrabajo3',
            field=models.CharField(default='', max_length=200, verbose_name='Foto del trabajo'),
            preserve_default=False,
        ),
    ]
