# Generated by Django 3.2.4 on 2021-07-08 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210707_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idHorario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del horario')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la persona')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo de la persona')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo de la persona')),
                ('fecha', models.CharField(max_length=50, verbose_name='Fecha del horario')),
            ],
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='fotoTrabajo',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='fotoTrabajo2',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='fotoTrabajo3',
        ),
        migrations.AddField(
            model_name='mecanico',
            name='fotoTrabajo',
            field=models.CharField(default='', max_length=200, verbose_name='Foto del trabajo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mecanico',
            name='fotoTrabajo2',
            field=models.CharField(default='', max_length=200, verbose_name='Foto del trabajo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mecanico',
            name='fotoTrabajo3',
            field=models.CharField(default='', max_length=200, verbose_name='Foto del trabajo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajo',
            name='fecha',
            field=models.CharField(default='', max_length=50, verbose_name='Fecha del trabajo'),
            preserve_default=False,
        ),
    ]
