# Generated by Django 3.2.4 on 2021-07-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mecanico_experienciamecanico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('idFoto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la foto')),
                ('linkFoto', models.CharField(default='foto.jpg', max_length=200, verbose_name='Link de la foto')),
            ],
        ),
    ]
