# Generated by Django 3.2.4 on 2021-07-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_carousel_slidecarousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='slideCarousel',
            field=models.CharField(default='', max_length=200, verbose_name='Slide del Carousel'),
        ),
    ]
